### PR TITLE
Add 24bit packed formats for dummy, ALSA, and PulseAudio

### PR DESCRIPTION
**Pull request by 0joshuaolson1**
For https://github.com/andrewrk/libsoundio/issues/94

PulseAudio 9.0 doesn't support unsigned packed 24LE/BE, so I lucked out on having a DAC I could test this patch with.

### CODE REVIEW

**Comment by andrewrk** [comment]
Nice! Seems simple enough. Does it work on your DAC?

**Comment by 0joshuaolson1** [comment]
Yep.

**Comment by andrewrk** [comment]
Cool. This is looking good.

I'm hoping to have some time this coming weekend to hazard some CoreAudio and WASAPI code to support these extra formats, or at least respond with the correct error code when attempting to use them.

Next I'm going to do some work to release the next minor bump version, and then we can merge this into master.

**Comment by 0joshuaolson1** [comment]
Good luck there. I can't test it.

**Comment by andrewrk** [comment]
merged into v2 branch

**Pull request closed without merging**
