### PR TITLE
Add SoundIoDevice accessors for non-C languages

### PR DESCRIPTION
**Pull request by 0joshuaolson1**

### CODE REVIEW

**Comment by andrewrk** [comment]
I'm not fundamentally opposed to this, but let's talk about it a little first. What language are you working with right now?

**Comment by 0joshuaolson1** [comment]
[Pony](https://github.com/ponylang/ponyc), so it's niche. These aren't the only additions one might want to make in this area, but for now I'm manually patching a synced fork.

**Comment by andrewrk** [comment]
What do the existing API bindings to libsoundio look like before this patch? E.g. in Python a binding looks like C++ code and probably also some Python code to interface with a C library. What does the existing bindings you have so far look like? Is there any C or C++ code that is part of the binding?

**Comment by 0joshuaolson1** [comment]
I was able to find [Lua](https://github.com/luapower/libsoundio/blob/master/libsoundio_h.lua), [Rust](https://github.com/klingtnet/rsoundio/blob/master/src/ffi/structs.rs), [Nim](https://github.com/ul/soundio/blob/master/src/soundio.nim), and [Ada] bindings. Nim compiles to C, Rust and Ada have more mature C pointer interoperation than Pony, and the Lua library is able to embed a large shim.

I don't know whether Python etc. would benefit, but [Julia](http://docs.julialang.org/en/release-0.4/manual/calling-c-and-fortran-code/) might. Unlike Swift's package manager but like Pony, I believe its only control over C is direct calls to dynamic/shared libraries. So I think shim code has to be manually compiled into a C library, whether it's a separate one using libsoundio or patched directly into it.

**Comment by 0joshuaolson1** [comment]
I hope I was informative, but I'm going to close this because Pony is turning out to be just too immature for good C library interop in general. You may find me messing with rsoundio.

**Pull request closed without merging**
