### PR TITLE
Adjust PulseAudio latency.

### PR DESCRIPTION
**Pull request by atsushieno**
This should fix https://github.com/andrewrk/libsoundio/issues/149

### CODE REVIEW

**Comment by andrewrk** [comment]
I know I played a lot with this flag and then ended up not using it. This was years ago though. What kind of testing have you done with these changes?

**Comment by atsushieno** [comment]
Similar to https://github.com/andrewrk/libsoundio/pull/188, I was trying to resolve issue I had in my app, trying any potential fixes. For audio latency I still have issues. That is more likely my code doesn't cope well with appropriate audio loop, so I can't tell if the changes really improve the situation. If you had a decision to not use the flag after some investigation, maybe that conclusion is more likely right.

**Comment by gavv** [comment]
Any news on this?

This flag forces PulseAudio to apply the configured latency to the underlying sink too, not just to the stream buffer (see [here](https://gavv.github.io/articles/pulseaudio-under-the-hood/#controlling-latency)). This means that without this flag the total playback latency (stream buffer + sink buffer) is actually undefined, which is obviously not suited for the real-time output.

**Comment by gavv** [comment]
BTW #209 and #176 are probably related.

**Comment by gavv** [comment]
It also seems that the documentation lies currently (until this PR is merged):

```
struct SoundIoOutStream {
    ...
    /// For PulseAudio, if you set this value to non-default, it sets
    /// `PA_STREAM_ADJUST_LATENCY` and is the value used for `maxlength` and
    /// `tlength`.
    ...
    double software_latency;
```

**Comment by dsego** [comment]
This PR seems to fix my problems with latency on Ubuntu 19.04.  In my source code I am trying to set a low software latency for my input stream with this  `instream.*.software_latency = 0.001;`.

I then check the info on my built-in mic with  `pactl list sources`*. The configured latency  in this case is  `341333 usec`.

After recompiling and installing libsoundio with the PA latency flags it returns `configured 2000 usec`.

Another trick I found to get a lower latency is to run PulseAudio Volume Control. It seems to reduce the latency to `configured 40000 usec`.

(*) https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/Developer/Clients/LatencyControl/

**Comment by gavv** [comment]
> In this case I believe that pavucontrol might be requesting a lower latency on the same source.

True. I've also encountered this.

**Pull request merged**
